[build]
command = "npm install && npm run build && pip install -r netlify/functions/generate-name/requirements.txt -t python --disable-pip-version-check"
publish = "dist"
functions = "netlify/functions"  

[[redirects]]
from = "/api/generate-name"
to = "/.netlify/functions/generate-name"
status = 200