[build]
command = "npm install && npm run build && pip install -r netlify/functions/requirements.txt -t netlify/functions"
publish = "dist"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200