[build]
command = "npm install && npm run build && go build -o netlify/functions/generate-name/generate-name netlify/functions/generate-name/generate-name.go"
publish = "dist"
functions = "netlify/functions"