[build]
command = "npm install && npm run build && pip install --system -r netlify/functions/requirements.txt"
publish = "dist"

[[redirects]]
from = "/api/generate-name"
to = "/.netlify/functions/generate-name"
status = 200